# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.controller_api import ControllerApi  # noqa: E501
from swagger_client.rest import ApiException
from pprint import pprint


class TestControllerApi(unittest.TestCase):
    """ControllerApi unit test stubs"""

    def setUp(self):
        # create an instance of the API class
        configuration = None
        self.api = ControllerApi(swagger_client.ApiClient(configuration))

    def tearDown(self):
        pass

    def test_add_socks(self):
        """Test case for add_socks
        """
        body = swagger_client.SockRequest(color="color", cotton_part="10", quantity="3") # SockRequest |
        api_response = self.api.add_socks(body)
        pprint(api_response)

    def test_delete_socks(self):
        """Test case for delete_socks
        """
        body = swagger_client.SockRequest(color="color", cotton_part="10", quantity="3") # SockRequest |
        api_response = self.api.delete_socks(body)
        pprint(api_response)

    def test_get_sock_quantity(self):
        """Test case for get_sock_quantity
        """
        color = "color" # str | 
        operation = "lessThan" # str | 
        cotton_part = 56 # int | 
        api_response = self.api.get_sock_quantity(color, operation, cotton_part)
        pprint(api_response)


if __name__ == '__main__':
    unittest.main()
